on: [push, pull_request]
jobs:
  job_id:
    strategy:
      matrix:
        platform: [ubuntu-latest,windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - run: g++ -o 0212 0212.cpp
    - run: ./0212
    - run: ./0212
